---

- src: "https://github.com/nexcess/ansible-role-server.git"
  name: "nexcess.server"
- src: "git+https://github.com/nexcess/ansible-role-datadog.git"
  name: "nexcess.datadog"
- src: "https://github.com/nexcess/ansible-haproxy.git"
  name: "nexcess.haproxy"
- src: "https://github.com/nexcess/ansible-role-apache.git"
  name: "nexcess.apache"
- src: "https://github.com/nexcess/ansible-role-php-mirror.git"
  name: "nexcess.php-mirror"
